#!/usr/bin/env node
// Export sized icon SVGs for Leopard AI / SonicFlow (SF-29).
//
// Reads:
//   brand/tokens.json           (color source of truth, read-only)
//   brand/assets/logomark.svg   (canonical geometric mark)
//
// Writes (overwrites):
//   brand/assets/icons/safari-16.svg
//   brand/assets/icons/safari-48.svg
//   brand/assets/icons/safari-128.svg
//   brand/assets/icons/ios-1024.svg
//   brand/assets/icons/app-512.svg
//   brand/assets/icons/favicon-16.svg
//   brand/assets/icons/favicon-32.svg
//
// Usage: node scripts/brand/export-icons.mjs
//
// Zero external dependencies. Idempotent: running twice on identical inputs
// yields byte-identical outputs. No hex literals live in this file — all colors
// come from brand/tokens.json.

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(here, "..", "..");
const tokensPath = resolve(repoRoot, "brand", "tokens.json");
const logomarkPath = resolve(repoRoot, "brand", "assets", "logomark.svg");
const outDir = resolve(repoRoot, "brand", "assets", "icons");

const tokens = JSON.parse(readFileSync(tokensPath, "utf8"));
const logomarkRaw = readFileSync(logomarkPath, "utf8");

const leopardBase = tokens.background.leopard.base;

// Targets are sorted by filename so iteration order is stable across runs.
const TARGETS = [
  { name: "app-512.svg", size: 512, withBackground: true },
  { name: "safari-128.svg", size: 128, withBackground: true },
  { name: "safari-16.svg", size: 16, withBackground: true },
  { name: "safari-48.svg", size: 48, withBackground: true },
  { name: "favicon-16.svg", size: 16, withBackground: true },
  { name: "favicon-32.svg", size: 32, withBackground: true },
  { name: "ios-1024.svg", size: 1024, withBackground: true },
];

mkdirSync(outDir, { recursive: true });

// Extract the logomark's <svg ...> inner content so we can nest it as a <symbol>.
const inner = extractSvgInner(logomarkRaw);

for (const t of TARGETS) {
  const svg = renderIcon({
    size: t.size,
    withBackground: t.withBackground,
    background: leopardBase,
    logomarkInner: inner,
  });
  writeFileSync(resolve(outDir, t.name), svg);
}

console.log("brand icons exported:");
for (const t of TARGETS) {
  console.log("  -", resolve(outDir, t.name));
}

// ---------------------------------------------------------------------------
// helpers
// ---------------------------------------------------------------------------

function extractSvgInner(svgText) {
  // Grab everything between the opening <svg ...> and the closing </svg>.
  const openMatch = svgText.match(/<svg\b[^>]*>/);
  if (!openMatch) throw new Error("logomark.svg: no <svg> root element");
  const openEnd = openMatch.index + openMatch[0].length;
  const closeIdx = svgText.lastIndexOf("</svg>");
  if (closeIdx < 0) throw new Error("logomark.svg: no closing </svg>");
  return svgText.slice(openEnd, closeIdx).trim();
}

function renderIcon({ size, withBackground, background, logomarkInner }) {
  // The logomark is authored in a 256x256 viewBox. We nest the same viewBox
  // here so the mark scales into the icon box intact. The outer <svg> uses
  // width/height = SIZE so consumers can drop it into favicon/manifest slots.
  const indent = "    ";
  const indented = logomarkInner
    .split("\n")
    .map((line) => (line.length ? indent + line : line))
    .join("\n");

  const lines = [];
  lines.push("<?xml version=\"1.0\" encoding=\"UTF-8\"?>");
  lines.push(
    `<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"${size}\" height=\"${size}\" viewBox=\"0 0 256 256\">`
  );
  lines.push(`  <title>Leopard AI — ${size}x${size}</title>`);
  lines.push(
    "  <desc>Generated by scripts/brand/export-icons.mjs from brand/assets/logomark.svg and brand/tokens.json.</desc>"
  );
  if (withBackground) {
    lines.push(`  <rect width=\"256\" height=\"256\" fill=\"${background}\"/>`);
  }
  lines.push("  <g>");
  lines.push(indented);
  lines.push("  </g>");
  lines.push("</svg>");
  lines.push("");
  return lines.join("\n");
}
