#!/usr/bin/env node
// Generate per-platform brand token files from brand/tokens.json.
// Source of truth: brand/tokens.json  (SF-23)
// Consumers: Safari/Web CSS and iOS/macOS Swift.
//
// Usage: node scripts/brand/generate-tokens.mjs
//
// Idempotent: running twice on the same input yields byte-identical output.

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(here, "..", "..");
const tokensPath = resolve(repoRoot, "brand", "tokens.json");
const outDir = resolve(repoRoot, "brand", "generated");

const tokens = JSON.parse(readFileSync(tokensPath, "utf8"));

mkdirSync(outDir, { recursive: true });

writeFileSync(resolve(outDir, "tokens.css"), renderCss(tokens));
writeFileSync(resolve(outDir, "BrandTokens.swift"), renderSwift(tokens));

console.log("brand tokens generated:");
console.log("  -", resolve(outDir, "tokens.css"));
console.log("  -", resolve(outDir, "BrandTokens.swift"));

// ---------------------------------------------------------------------------
// CSS
// ---------------------------------------------------------------------------

function renderCss(t) {
  const lines = [];
  lines.push("/* AUTOGENERATED from brand/tokens.json — do not edit by hand.");
  lines.push(" * Regenerate: node scripts/brand/generate-tokens.mjs");
  lines.push(` * Version: ${t.meta.version}`);
  lines.push(" */");
  lines.push(":root {");
  lines.push("  color-scheme: dark;");
  lines.push("");
  lines.push("  /* chakra palette */");
  for (const [key, v] of Object.entries(t.palette.chakra)) {
    lines.push(`  --chakra-${kebab(key)}: ${v.hex};`);
  }
  lines.push("");
  lines.push("  /* neutral */");
  for (const [key, v] of Object.entries(t.palette.neutral)) {
    const value = v.hex ?? v.rgba;
    lines.push(`  --neutral-${kebab(key)}: ${value};`);
  }
  lines.push("");
  lines.push("  /* accent */");
  for (const [key, v] of Object.entries(t.palette.accent)) {
    lines.push(`  --accent-${kebab(key)}: ${v.hex};`);
  }
  lines.push("");
  lines.push("  /* mode accents */");
  for (const [mode, v] of Object.entries(t.mode)) {
    lines.push(`  --mode-${kebab(mode)}: ${v.hex};`);
  }
  lines.push("");
  lines.push("  /* typography */");
  lines.push(`  --font-display: ${t.typography.display};`);
  lines.push(`  --font-body: ${t.typography.body};`);
  lines.push(`  --font-mono: ${t.typography.mono};`);
  lines.push("");
  lines.push("  /* radius */");
  for (const [key, v] of Object.entries(t.radius)) {
    lines.push(`  --radius-${kebab(key)}: ${v}px;`);
  }
  lines.push("");
  lines.push("  /* spacing */");
  for (const [key, v] of Object.entries(t.spacing)) {
    lines.push(`  --space-${kebab(key)}: ${v}px;`);
  }
  lines.push("");
  lines.push("  /* elevation */");
  lines.push(`  --elev-soft: ${t.elevation.soft};`);
  lines.push(`  --elev-gold: ${t.elevation.gold};`);
  lines.push("");
  lines.push("  /* leopard background */");
  lines.push(`  --leopard-base: ${t.background.leopard.base};`);
  lines.push(`  --leopard-spot: ${t.background.leopard.spot};`);
  lines.push(`  --leopard-ring: ${t.background.leopard.ring};`);
  lines.push(`  --leopard-opacity: ${t.background.leopard.opacity};`);
  lines.push(`  --leopard-blur: ${t.background.leopard.blurPx}px;`);
  lines.push("}");
  lines.push("");
  return lines.join("\n");
}

// ---------------------------------------------------------------------------
// Swift
// ---------------------------------------------------------------------------

function renderSwift(t) {
  const lines = [];
  lines.push("// AUTOGENERATED from brand/tokens.json — do not edit by hand.");
  lines.push("// Regenerate: node scripts/brand/generate-tokens.mjs");
  lines.push(`// Version: ${t.meta.version}`);
  lines.push("");
  lines.push("import SwiftUI");
  lines.push("");
  lines.push("public enum BrandTokens {");
  lines.push("  public enum Chakra {");
  for (const [key, v] of Object.entries(t.palette.chakra)) {
    lines.push(`    public static let ${camel(key)} = Color(hex: "${v.hex}")`);
  }
  lines.push("  }");
  lines.push("");
  lines.push("  public enum Neutral {");
  for (const [key, v] of Object.entries(t.palette.neutral)) {
    if (v.hex) {
      lines.push(`    public static let ${camel(key)} = Color(hex: "${v.hex}")`);
    }
  }
  lines.push("    public static let panel = Color.black.opacity(0.78)");
  lines.push("  }");
  lines.push("");
  lines.push("  public enum Accent {");
  for (const [key, v] of Object.entries(t.palette.accent)) {
    lines.push(`    public static let ${camel(key)} = Color(hex: "${v.hex}")`);
  }
  lines.push("  }");
  lines.push("");
  lines.push("  public enum Mode {");
  for (const [mode, v] of Object.entries(t.mode)) {
    lines.push(`    public static let ${camel(mode)} = Color(hex: "${v.hex}")`);
  }
  lines.push("  }");
  lines.push("");
  lines.push("  public enum Radius {");
  for (const [key, v] of Object.entries(t.radius)) {
    lines.push(`    public static let ${camel(key)}: CGFloat = ${v}`);
  }
  lines.push("  }");
  lines.push("");
  lines.push("  public enum Spacing {");
  for (const [key, v] of Object.entries(t.spacing)) {
    lines.push(`    public static let ${camel(key)}: CGFloat = ${v}`);
  }
  lines.push("  }");
  lines.push("");
  lines.push("  public enum Leopard {");
  lines.push(`    public static let base = Color(hex: "${t.background.leopard.base}")`);
  lines.push(`    public static let spot = Color(hex: "${t.background.leopard.spot}")`);
  lines.push(`    public static let ring = Color(hex: "${t.background.leopard.ring}")`);
  lines.push(`    public static let opacity: Double = ${t.background.leopard.opacity}`);
  lines.push(`    public static let blurRadius: CGFloat = ${t.background.leopard.blurPx}`);
  lines.push(`    public static let spotCount: Int = ${t.background.leopard.spotCount}`);
  lines.push(`    public static let spotMinPx: CGFloat = ${t.background.leopard.spotMinPx}`);
  lines.push(`    public static let spotMaxPx: CGFloat = ${t.background.leopard.spotMaxPx}`);
  lines.push("  }");
  lines.push("}");
  lines.push("");
  return lines.join("\n");
}

// ---------------------------------------------------------------------------
// helpers
// ---------------------------------------------------------------------------

function kebab(s) {
  return s.replace(/([a-z0-9])([A-Z])/g, "$1-$2").toLowerCase();
}

function camel(s) {
  // already camel in most keys; normalize just in case.
  return s.replace(/[-_](.)/g, (_, c) => c.toUpperCase()).replace(/^./, (c) => c.toLowerCase());
}
